### ISSUE TITLE
Something wrong during setup?

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#125]
Games look stalled during setup phase.
Examples 
https://gaiaform.io/game/inspiring-horse-6296
https://gaiaform.io/game/menacing-jeans-2572

**Comment by coyotte508** [comment]
It's the turnOrderDesc PR for viewer messing up

**Comment by coyotte508** [comment]
It was `passedPlayers` being undefined, fixed in the viewer.

You can catch those errors by running the website locally (before upgrading on the remote)
