### ISSUE TITLE
Possible bug in leeching

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#142]
In engine.ts we are assuming
 ```
      // If the player has passed and it's the last round, there's absolutely no points in leeching
      // There's no cultists in gaia project.
      if (this.isLastRound && this.passedPlayers.includes(pl.player)) {
        pl.data.leechPossible = 0;
        continue;
      }
```
but if leeching is for free it could make sense

**Comment by rzulian** [comment]
Right. Dejavu ;)

**Comment by coyotte508** [comment]
https://boardgamegeek.com/article/30060833#30060833

**Comment by rzulian** [comment]
No! ;) We are reverting our own roles here :)))
On page 16 " You can take free actions before you pass but not after (passion is an action)".
So in round 6, you continue to leech, but you cannot convert.

**Comment by coyotte508** [comment]
Yes, but german rules state:

> Übrige Ressourcen bringen ebenfalls noch Punkte: je 3 Credits/Wissen/Erz (in beliebiger Kombination) sind 1 Punkt wert. Dafür dürft ihr am Spielende noch einmal beliebig viele freie Aktionen nutzen, um eure restlichen Ressourcen in diese umzuwandeln.

> Other resources also earn points: 3 credits each / knowledge / ore (in any combination) are worth 1 point. At the end of the game you can use as many free actions as you like to turn your remaining resources into these.

http://www.feuerland-spiele.de/dateien/Gaia_Project_web.pdf

German rules *allow* additional free actions (as an exception, I imagine) at the end of the game...

**Comment by rzulian** [comment]
I've asked Helge and he just answered: "at the end of the game, after all players have passed, everybody can do as many free conversions as they like to change all remaining resources into points.

That is the resources scoring, it includes free conversions! (And the english rules are not clear enough in this regard)."
I've to add that also the Italian rules are incomplete, probably translated form the English version.
But I've also to add that we usually play the right way, so probably in the past we double checked. That's way I was asking.
I'm going to post in the BGG forum the answer
