### ISSUE TITLE
Bug in turn order

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#143]
Game https://gaiaform.io/game/welcome-everyone
Gleens passed as first in round4, but are listed as last in turn 5.
@coyotte508

**Comment by coyotte508** [comment]
That's a viewer problem, because it shows the current player as the first and then loops around.

Maybe it shouldn't do that in the income phase or gaia phase. Feel free to reopen the issue in viewer, but don't worry there won't be any behavior problem

**Comment by rzulian** [comment]
Yes, just had a look at the log. I'll reopen it in the viewer, because it's to misleading
