### ISSUE TITLE
Itars when using gaia phase

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#154]
This is requiring a rule verification.
You have 6 tokens in Gaia bowl.
During the gaia phase you decide to discard 4 tokes to get a tech tile. If through the advancement in the research area you get to charge 3 powers, the 2 tokens left, are considered already in Bowl 1, therefore you can move them, or are they still in the Gaia bowl?

**Comment by rzulian** [comment]
https://boardgamegeek.com/article/30086989#30086989

**Comment by coyotte508** [comment]
Needs official ruling!

**Comment by rzulian** [comment]
From Helge, he responded on the thread:
"Return two power tokens from Gaia bowl into bowl 1, discard the remaining 4 power tokens, charge 3 power as result from the tech advancement - this is a valid order!"

**Comment by coyotte508** [comment]
So basically the player can choose order. Nice. We need a new command "transfer power" or w/e.

**Comment by rzulian** [comment]
Update: so Helge revised his comment. The current implementation is correct!
