### ISSUE TITLE
Wrong federation for Ivits

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#160]
In this game https://gaiaform.io/game/three, move 267. 
Ivits can form a federation. Before the latest change on the federation it wasn't possible for him to for a federation after he got the q. But now he can. Problem is that the Q count goes to -1. The new federation algorithm is counting existing and needed satellites

**Comment by coyotte508** [comment]
Turns out this was an older problem.

And La Bestia should have had one more qic, that he lost when forming an earlier federation!
