### ISSUE TITLE
PI: Itars doesn't have automatic 1pw?

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#162]

**Comment by coyotte508** [comment]
?

If you're referring to the autoleech, randomboolean (rdk) made the remark that sometimes they want to keep tokens in area 2 in order to be able to burn them, so that they land in the gaia area and they can gain tech tiles.

**Comment by rzulian** [comment]
I see. Line 366 in engine.ts. Why round<6 ?

**Comment by coyotte508** [comment]
Because there's no gaia phase after round 6, so it's useless to put tokens in gaia area.
