### ISSUE TITLE
Bug in Gleens +2vp for Gaia

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#180]
Game https://gaiaform.io/game/Gianluigi-Buffon
Gleens have now 65vp
If you play the game locally the have 55vp.
They are receiving +2vp for a gaia planet. This is the log in the site

<img width="1434" alt="screen shot 2018-10-11 at 21 48 28" src="https://user-images.githubusercontent.com/29941924/46830045-cf869d00-cd9f-11e8-9b56-63b170416e92.png">

this is the log locally

<img width="1436" alt="screen shot 2018-10-11 at 21 48 07" src="https://user-images.githubusercontent.com/29941924/46830049-d57c7e00-cd9f-11e8-8307-ea14d408287f.png">

Any clue?

**Comment by coyotte508** [comment]
I had the same problem on another game, replayed on the site,a nd it worked fine.

I assume it was a past bug?

**Comment by coyotte508** [comment]
Uh.

https://gaiaform.io/game/timid-front-3625

This is a current game, they don't get the points

**Comment by coyotte508** [comment]
The issue can probably be explained by the fact that gleens gaining victory points used to be an event as starting income in the faction board, and now it's through a handler.

Games ongoing during the switch would have both. It doesn't explain why in https://gaiaform.io/game/timid-front-3625, before I replayed, gleens didn't get points for planets on gaia.

**Comment by rzulian** [comment]
@coyotte508 : I've created v2.5.6 to manage Gianluigi-Buffon, but I cannot replay it because I'm getting the same error from the site. I think is about the EngineOptions

**Comment by rzulian** [comment]
Tried now and it worked fine 👍
