### ISSUE TITLE
Bug : zero point on final scoring

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#190]
If you didn’t advance in a final scoring, you don’t get any point (e.g. in a tre player game you don’t Gaiaform any Gaia with Gaia as final scoring)

**Comment by coyotte508** [comment]
So, a player should get no point in final scoring if they didn't advance at least once? 

I don't find the relevant bit in the english rules (page 18). Is it in the german rules?

**Comment by rzulian** [comment]
This is the discussion in BGG https://boardgamegeek.com/thread/1929227/0-end-score-0-vp
Helge responded in page 1

**Comment by coyotte508** [comment]
Ok. Let's just add a link to this thread in the comments in the code.
