### ISSUE TITLE
Free actions are not clearing fed cache

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#193]
If you convert O to token, available federations should be recalculated.

Add line in engine.ts 1450: pl.federationCache = null ;

**Comment by rzulian** [comment]
In this game https://gaiaform.io/game/SalmurOnTheBoard, Nevlas can convert two ore and form a federation with 12 satellites, but they are not getting the option to form a federation. If cache is cleared, then probably this is related to #194

**Comment by coyotte508** [comment]
This is not a cache problem, the problem still happens with federation cache disabled.

This is the current heuristic for finding federations that is not working (it should work fine for 4-5 building groups, there are 7 here).

I'll add a custom federation option if the player has 8+ satellites and 6+ building groups with the sum of their power values being <= 7.
