### ISSUE TITLE
No fed proposed

### ISSUE THREAD

**Issue by rzulian** [donkeytech/gaia-engine#199]
In this game https://gaiaform.io/game/The_wake_of_magellan
Ivits should be able to for a federation connecting the main fed with the 2 mines+station, using the available qic, that he just got upgrading to lab and advancing int.

This is not working online, but works locally. @coyotte508 is there an misalignment between the online version and the repo?

**Comment by coyotte508** [comment]
Sorry, just saw the issue. Should be same version (except for a commit about publishing, it seems). I'll make sure to push this when I get back.

From what is displayed, it seems that only 26 building power is counted instead of 27 for the existing federation.

**Comment by rzulian** [comment]
The building power is correctly 26, but the federation cache is wrong, counting 2 availableSatellites (QICs) instead of just one. Locally is correct.
<img width="710" alt="Screenshot 2019-04-23 at 11 37 28" src="https://user-images.githubusercontent.com/29941924/56571543-6f2daf00-65bd-11e9-8077-2596b3634cb4.png">
