### ISSUE TITLE
Reorganize data

### ISSUE THREAD

**Issue by coyotte508** [donkeytech/gaia-engine#64]
Engine has advTechTiles, techTiles, roundScoringTiles, finalScoringTiles, roundBoosters.

Why not do something like that:

```ts
class Engine {
  tiles: {
    tech: {
      normal: [],
      advanced: []
    },
    scoring: {
      round: [],
      final: []
    },
    boosters: [],
    federations: []
  }
}
```

**Comment by coyotte508** [comment]
Techs could be merged on multiple levels. No need for distinction between advanced or normal, it can easily be done by `Object.values(TechTilePos).includes(pos)`.

In `PlayerData`, the building counts should probably in a `buildings` variable.

**Comment by rzulian** [comment]
Consider also to manage greenFederation and countFederation as property of the the federationTile
