### ISSUE TITLE
The increase range action can be combined with start a gaia project

### ISSUE THREAD

**Issue by coyotte508** [donkeytech/gaia-engine#66]
> As a special action, you can take a “Build a Mine” action or “Start a 
Gaia Project” with your basic range increased by three. The 
normal rules for the actions apply. This action cannot be 
combined with another action.

Not just build a mine

**Comment by rzulian** [comment]
It's implemented in the current `Engine.buildMinePhase`, which filter for Mines and Gaiaformers.
