### ISSUE TITLE
Players cannot use free actions after their final Pass

### ISSUE THREAD

**Issue by coyotte508** [donkeytech/gaia-engine#68]
We should convert all the power tokens into credits, and qic into ore, when they pass, not when the game ends.

We should also decline all leech after a player passes in the 6th round.

**Comment by rzulian** [comment]
It's wrong. An opponent can charge power even if he passed, but yes, he cannot do any more free actions

**Comment by coyotte508** [comment]
I mean, there's no point in charging power after passing, after the 6th round.

You can only lose victory points, and you will gain nothing as you can't convert the power charged into resources.

**Comment by rzulian** [comment]
That's true, unless you get more "1 charge power"s, which are for free, and you can get more VPs

**Comment by coyotte508** [comment]
You can't gain VP from free leech after you've passed. Since you can't convert them to credits, you can't get victory points from them.

Victory points are for credits, ore & knowledge. Not for power tokens.

**Comment by rzulian** [comment]
Ahh, yes, right!
